export const PROMPT_TEMPLATES = [
  "Summarize this",
  "Translate to French",
  "Fix grammar",
  "Make it more concise",
  "Explain like I’m five",
  "Turn this into a tweet",
  "Write a professional email",
  "Add examples",
  "Convert to bullet points",
  "Make it sound more friendly",
  "Explain step by step",
  "Translate to Hindi",
  "Generate a title",
  "Write a conclusion",
  "Rewrite in passive voice",
  "Suggest improvements",
  "Convert to formal tone",
  "Paraphrase this",
];
